# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8c3f4da36c02c142f183893976f5b4d276e2f19d15e8411ec6c26f44a691c2a2c51a62e6fa69925dc520cf450c0007b0187f2561d58de7e10abd90496171e6d

test:
  secret_key_base: ab0f2c8f64a04b35b1d6be08419aeaafc167787835ec1417382a9c1bb84f4c6cefbf9c3bb25b0a4c45961b4c48ef96ae8e3ecc31a09b49ec81f9d9375a2f4350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
